name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger on pull requests.
  pull_request:

  # Trigger on pushes to the mainline branches. This prevents building commits twice when the pull
  # request source branch is in the same repository.
  push:
    branches:
      - "main"

  # Trigger on request.
  workflow_dispatch:

jobs:
  flow-status:
    name: flow-status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: '3.10'
      - uses: actions/cache@v3.2.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install signac
        run: python3 -m pip install -r .github/workflows/requirements-test.txt
      - name: Initialize workspace
        run: python3 hoomd_validation/init.py
      - name: Check flow status
        run: python3 hoomd_validation/project.py status
