name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger on pull requests.
  pull_request:

  # Trigger on pushes to the mainline branches. This prevents building commits twice when the pull
  # request source branch is in the same repository.
  push:
    branches:
      - "main"

  # Trigger on request.
  workflow_dispatch:

jobs:
  # for now the repo is private, so pre-commit won't run automatically
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.0.2

      - name: Install Python
        uses: actions/setup-python@v3

      - name: Run pre-commit hooks
        uses: pre-commit/action@v2.0.3

  flow-status:
    name flow-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.10'
      - uses: actions/cache@v3.0.11
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install signac
        run: python3 -m pip install -r .github/workflows/requirements-test.txt
      - name: Initialize workspace
        run: python3 hoomd_validation/init.py
      - name: Check flow status
        run: python3 hoomd_validation/project.py status
