name: Unit test

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:

  push:
    branches:
    - "main"

  workflow_dispatch:

jobs:
  status:
    name: Initialize and show status
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: "3.12"
    - name: Set up Python environment
      uses: glotzerlab/workflows/setup-uv@1fe577d5430222a9793694a14cdb316cf8f720e1 # 0.9.0
      with:
        lockfile: ".github/workflows/requirements-test.txt"
    - name: Initialize workspace
      run: python3 hoomd_validation/project.py init
    - name: Show workflow
      run: cat --number workflow.toml
    - name: Set up row
      uses: glotzerlab/workflows/setup-row@1fe577d5430222a9793694a14cdb316cf8f720e1 # 0.9.0
    - name: Show project status
      run: row show status

  # This job is used to provide a single requirement for branch merge conditions.
  tests_complete:
    name: All tests
    if: always()
    needs: [status]
    runs-on: ubuntu-24.04

    steps:
    - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Done
      run: exit 0
