name: Unit test

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:

  push:
    branches:
    - "main"

  workflow_dispatch:

jobs:
  status:
    name: Initialize and show status
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.14"
    - name: Set up Python environment
      uses: glotzerlab/workflows/setup-uv@00c67cb577c36bdc2570845fc62d1a30e3383012 # 0.14.0
      with:
        lockfile: ".github/workflows/requirements-test.txt"
    - name: Initialize workspace
      run: python3 hoomd_validation/project.py init
    - name: Show workflow
      run: cat --number workflow.toml
    - name: Set up row
      uses: glotzerlab/workflows/setup-row@00c67cb577c36bdc2570845fc62d1a30e3383012 # 0.14.0
    - name: Show project status
      run: row show status

  # This job is used to provide a single requirement for branch merge conditions.
  tests_complete:
    name: All tests
    if: always()
    needs: [status]
    runs-on: ubuntu-24.04

    steps:
    - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Done
      run: exit 0
