name: Unit test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

  push:
    branches:
    - "main"

  workflow_dispatch:

jobs:
  status:
    name: Initialize and show status
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Set up Python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: "3.12"
    - name: Set up Python environment
      uses: glotzerlab/workflows/setup-uv@ae7e7c6931098a313ef8069ef04b88a55c3a40f6 # 0.3.0
      with:
        lockfile: ".github/workflows/requirements-test.txt"
    - name: Initialize workspace
      run: python3 hoomd_validation/project.py init
    - name: Show workflow
      run: cat --number workflow.toml
    - name: Set up row
      uses: glotzerlab/workflows/setup-row@ae7e7c6931098a313ef8069ef04b88a55c3a40f6 # 0.3.0
    - name: Show project status
      run: row show status
